name: CI

on:
  push:
    branches:
      - main

jobs:
  update-datas:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update script
        run: |
          # Seu script de atualização aqui
